FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
COPY backend/package*.json ./backend/
COPY frontend/package*.json ./frontend/
COPY shared/package*.json ./shared/
RUN npm ci
COPY . .
EXPOSE 8080
CMD ["npm", "run", "dev", "-w", "backend"]
